AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/vpc.yaml

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/ec2.yaml
      Parameters:
        VpcOut: !GetAtt VPCStack.Outputs.VpcOut
        PublicSubnet1Out: !GetAtt VPCStack.Outputs.PublicSubnet1Out

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/rds.yaml
      Parameters:
        SecurityGroupOut: !GetAtt EC2Stack.Outputs.SecurityGroupOut
        PrivateSubnet1Out: !GetAtt VPCStack.Outputs.PrivateSubnet1Out
        PrivateSubnet2Out: !GetAtt VPCStack.Outputs.PrivateSubnet2Out
        
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/iac-bucket-azamcloud/s3.yaml

